57 feature ranking api contect
woohaengshi/frontend pull request #61
Opened 2024-08-15 14:08 UTC by doyi0107

## 📋 연관된 이슈 번호
- #57

## 🛠 구현 사항
- 랭킹 API 연결 
- type 따로 분리

## 🧐변경사항 
- api폴더명 뒤에 Api라고 명시하는 거 어떤가요, type도 마찬가지로요!!

## 🏜 스크린샷
![image](https://github.com/user-attachments/assets/b4f3155f-eb6c-4424-a5a7-e2aa79db2938)
![image](https://github.com/user-attachments/assets/489de775-1f2d-443c-af4d-2afc29c37e5b)

2024-08-15 15:05 UTC, riverkite0708 commented on components/study/SubjectEditForm.tsx
> +  }));
여기를 `const { subjects, selectedSubjects, isEditing, setEditing, saveSelected, saveEditing } = useSubjectStore(); ` 이렇게 쓰면 안돌아갈까요? 전 그냥 `스토어명()` 했는데 문제없이 코드 돌아갔던것 같아서 질문합니다~ (zustand 잘 모릅니다!!!)

2024-08-15 15:12 UTC, riverkite0708 commented on components/study/SubjectEditForm.tsx
> +          onSaveEditing={handleSaveAndClose} // 저장 및 모달 닫기
마찬가지로 여기도  `onAddSubject={(subject) => addSubject(subject)}` 이런식으로 줄이는건 안되는건지 질문!! 그리고 zustand를 사용하니까 props로 내려주는게 아니라 각각 컴포넌트에서 한번만 호출하면 되지 않을까요? 아래 SubjectSelect.tsx에서 똑같이  `import { useSubjectStore } from '../../store/subjectStore';`를 import 하고 있는것 같습니다!

2024-08-15 15:22 UTC, riverkite0708 requested changes
모처럼 휴일에다 약속까지 있었다고 들었는데 수고많았어요!! 😎

2024-08-15 15:22 UTC, riverkite0708 commented on components/study/SubjectEditForm.module.css
딴소린데 컴포넌트명이 좀 헷갈려서 파일명을 SubjectForm으로 바꾸는건 어떤지 제안합니다!!! 아니면 SubjectForm, SubjectEditForm, SubjectSelectForm도 괜찮은것 같아요~ (이제와서 이런 파일명 수정 제안... 정말 죄송...)

2024-08-15 15:22 UTC, riverkite0708 commented on components/study/SubjectSelect.tsx
> +import { useSubjectStore } from '../../store/subjectStore';
`'@/store/subjectStore';`으로 경로를 수정하면 조금 더 직관적이고 좋을것 같아요~ ^__^

2024-08-15 15:22 UTC, riverkite0708 commented on store/subjectStore.ts
interface와 store 한개가 너무 길어지는것 같은데 수정/삭제/추가/선택/편집 등등... 기능별로 분리하면 조금 더 가독성이 좋아지지 않을까 싶습니다!!

2024-08-15 23:26 UTC, doyi0107 commented on components/study/SubjectEditForm.module.css
넵!! 반영하겠습니다

2024-08-15 23:26 UTC, doyi0107 commented on components/study/SubjectSelect.tsx
> +import { useSubjectStore } from '../../store/subjectStore';
확인!!

2024-08-16 00:58 UTC, Kong-E commented on store/subjectStore.ts
저도 재연님이 제안한 방식 좋아용

2024-08-16 01:08 UTC, Kong-E reviewed
저도 파일명 뒤에 API 붙이는거 좋아요!

2024-08-16 01:22 UTC, Kong-E commented on components/study/SubjectEditForm.tsx
> +  }));
저도 스토어명()으로만 했습니다!

2024-08-16 02:18 UTC, Kong-E commented on app/ranking/page.tsx
>  function Ranking() {
`export default function Ranking() {`

이렇게 해야 린트 에러 안날 것 같아요!

2024-08-16 02:18 UTC, Kong-E commented on app/ranking/page.tsx
> +      try {
try catch가 instance에도 있고 rankingApi에도 있어서 여긴 없어도 되지 않을까요??! (가독성 때메...)

2024-08-16 02:18 UTC, Kong-E commented on app/ranking/page.tsx
추후 리팩토링 방법 생각))
- 일간, 주간, 월간 각각 클라이언트 컴포넌트 분리
- page 컴포넌트는 서버 컴포넌트로 관리하고 컴포넌트에 async 붙여서 데이터 바로 페칭하기 (useEffect 사용하지 않는 방식)

2024-08-16 02:18 UTC, Kong-E commented on components/ranking/fullRankingList.tsx
> +  const formatTime = (timeInSeconds: number) => {
이런 유틸 함수는 utils 폴더 만들어서 관리해도 좋을 것 같습니다!!
( 저도 아직 이런 함수 utils 폴더로 안뺌)

2024-08-16 02:20 UTC, Kong-E commented on components/study/SubjectEditForm.tsx
> +          onSaveEditing={handleSaveAndClose} // 저장 및 모달 닫기
> 마찬가지로 여기도 `onAddSubject={(subject) => addSubject(subject)}` 이런식으로 줄이는건 안되는건지 질문!! 그리고 zustand를 사용하니까 props로 내려주는게 아니라 각각 컴포넌트에서 한번만 호출하면 되지 않을까요? 아래 SubjectSelect.tsx에서 똑같이 `import { useSubjectStore } from '../../store/subjectStore';`를 import 하고 있는것 같습니다!

굿굿

2024-08-16 02:52 UTC, doyi0107 commented on app/ranking/page.tsx
추후에 반영하겠습니다!!

2024-08-16 07:02 UTC, merged